# Generated by Django 4.0.4 on 2022-08-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arigonggan', '0002_question_delete_seat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
